### ISSUE TITLE
Jenkins "master" website publishing job fails

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/packages#194]
Since 1st of February: https://ci.eclipse.org/packages/job/Website/job/master/103/

Cause:
```
...
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...
```

As a result, the latest 2 changes to the Packages charts were not yet published.

**Comment by calohmn** [comment]
Since the above error is also in the last successful run (https://ci.eclipse.org/packages/job/Website/job/master/102/console), I guess the error is more likely around here:
````
[Pipeline] { (Jekyll Dependencies)
[Pipeline] dir
Running in /home/jenkins/agent/workspace/Website_master/build/homepage
[Pipeline] {
[Pipeline] sh
+ cp -rd /usr/gem/. /usr/local/bundle/
````

**Comment by calohmn** [comment]
The Jekyll image is loaded with tag `4`. Up until recently, it looks like this meant `4.1.0`. But the last runs seem to have pulled `4.2.0`. So something must have changed there, so that `cp -rd /usr/gem/. /usr/local/bundle/` fails with that version.
Workaround is to use `4.1.0` explicitly. I've triggered one Jenkins run manually with that version so that the newest charts are now published.
@ctron @thjaeckle I've had a brief look into the Jekyll 4.2.0 release notes but didn't see anything which could explain the issue here. Do you have an idea? Otherwise I would suggest to stick to 4.1.0 for now.

**Comment by thjaeckle** [comment]
@calohmn I have no idea what the issue would be with 4.2.0
I think pinning the version is a good thing in general to not get into troubles with a running system, so that's cool with me.

**Comment by calohmn** [comment]
I've changed the Jenkinsfile now to explicitly use version 4.1.0.

**Comment by ctron** [comment]
I had some issued with their container image in the past. Semantic versioning doesn't seem to mean much in this case. As we are only generating stuff with that, as long as it works, I would stick to a specific version if that solves the issue.
