### ISSUE TITLE
Allow overriding the hono release name

### ISSUE THREAD

**Issue by vhdirk** [eclipse/packages#430]
When deploying hono, it always prefixes the pods (amongst other things) with `.Release.Name`. Almost all other helm charts we use (including Ditto) allow overriding the release name with a custom value.

In our case, ArgoCD sets the Release name to something silly, so we'd like the option to specify the release name ourselves.   
See: https://github.com/eclipse/packages/blob/master/charts/ditto/templates/_helpers.tpl#L14 and https://github.com/eclipse/packages/blob/master/charts/ditto/templates/connectivity-deployment.yaml#L17

**Comment by sophokles73** [comment]
You can set the release name on the command line when installing a release using Helm:
```bash
helm install MY-RELEASE-NAME eclipse-iot/hono ....
```
May I ask why you feel that ArgoCD picking a random release name is a problem for you and what kind of naming pattern you would like to be able to set for e.g. services, pods etc.?

**Comment by BobClaerhout** [comment]
The release-name contains the environment name as well. As a result, the services also contain this environment name. This means that we have `dev-hono-service-device-registry` and `prod-hono-service-device-registry`. Aligning these service names eases things up

**Comment by sophokles73** [comment]
> Aligning these service names eases things up

Would you mind explaining what exactly *needs to be aligned* here?

**Comment by BobClaerhout** [comment]
If the device-registry service would be named `hono-service-device-registry` or `service-device-registry` in all environments, that would ease things up in the configuration of different environments.

**Comment by sophokles73** [comment]
With *different environments* you mean multiple, separate *releases* (using Helm parlais), right?
My understanding is that you want to be able to run e.g.
```bash
helm install instance-1 eclipse-iot/hono -n ns1 ...
helm install instance-1 eclipse-iot/hono -n ns2 ...
```
but have the registry service being named uniformly (e.g. `hono-service-device-registry`) in **both** namespaces, right? You could then use the same configuration (value.yaml) for all installations with only minimal adaptation ...

**Comment by BobClaerhout** [comment]
yes, exactly

**Comment by sophokles73** [comment]
The chart currently incorporates the release name into the name of all resources. This decision had originally been made to allow users to install multiple releases into the same k8s name space. This may or may not be a relevant use case, my feeling is that it is not because you could always simply install each release into its own k8s name space (as you seem to do @BobClaerhout).

That said, I believe we could alter the chart's templates in a way that would still (by default) use the old naming scheme but would also support using *static* names for the resources, i.e. without including the release name. However, I would rather try to make the templates less complicated by using *static* resource names by default, i.e. not including the release name anymore at all.

In particular, this should also make it easier for (k8s cluster internal) clients to look up a Service resource because it no longer needs to know the name of the release that the service belongs to. I also think that this would help with #252 because we could then set the same *static* service names for the SANs in the certificates used for the service endpoints.

We would, however, need to keep in mind that this would constitute a breaking change to the chart, so we would need to use a new major version and also adapt the cloud2edge package accordingly.

WDYT? @BobClaerhout @vhdirk @calohmn

**Comment by BobClaerhout** [comment]
I agree with your conclusion and proposal and I vote for having those static names. In our use case (we are even using different K8S clusters for each each release) that's exactly what we want.

**Comment by calohmn** [comment]
In terms of the naming scheme for the K8s resource names, I think the Hono chart should adhere to common practises used in many charts.
Looking at various charts (in the bitnami repo for example) and also looking at the output when using [helm create <chartName>](https://helm.sh/docs/helm/helm_create/), to me it seems the common way is the following:


The standard prefix for resource names is
`{ReleaseName}-{chartName}` 
_(or `{ReleaseName}` if ReleaseName contains chartName)_

If a value for `nameOverride` has been set, the prefix is
`{ReleaseName}-{nameOverride}`  
_(or `{ReleaseName}` if ReleaseName contains nameOverride)_

If `fullnameOverride` has been set, the prefix is
`{fullnameOverride}`


The Ditto and Hawkbit charts use the same naming scheme, by using the corresponding `ditto.fullname` and `hawkbit.fullname` template functions (containing the standard logic also created via `helm create`). 

In Hono, the existing `hono.fullname` function isn't being used currently. 
The resource prefix is currently always `{ReleaseName}`.
PR #416 changes that, making the naming scheme equivalent to the one in Ditto and Hawkbit (and various other charts).

> That said, I believe we could alter the chart's templates in a way that would still (by default) use the old naming scheme but would also support using _static_ names for the resources, i.e. without including the release name. 

With the naming scheme above, _static_ names can be achieved by setting `fullnameOverride`.
The old naming scheme could be achieved by setting `fullnameOverride` or `nameOverride` to the used release name or using `hono` as release name.


> However, I would rather try to make the templates less complicated by using _static_ resource names by default, i.e. not including the release name anymore at all.
> 
> In particular, this should also make it easier for (k8s cluster internal) clients to look up a Service resource because it no longer needs to know the name of the release that the service belongs to. I also think that this would help with #252 because we could then set the same _static_ service names for the SANs in the certificates used for the service endpoints.

I think if such (k8s cluster internal) clients are deployed within the same namespace via an adapted Hono Helm chart, the client can be parametrized via the same `hono.fullname` template function as the other Hono resources.

With regards to #252, I think the already mentioned certmanager approach would be an alternative.

All in all, I would vote for using the above standard naming scheme, the same as for Hono and Hawkbit, going forward with #416.

**Comment by sophokles73** [comment]
> With the naming scheme above, static names can be achieved by setting *fullnameOverride*.
The old naming scheme could be achieved by setting *fullnameOverride* or *nameOverride* to the used release name or using hono as release name.

Let's try an example using this strategy. Using `eclipse-hono` as the release name and setting *fullnameOverride* to `my-hono` will result in the Secret that holds the key and cert for the Kafka broker to have the name `my-hono-kafka-example-keys`.

The name of this Secret needs to be specified in *kafka.auth.tls.existingSecrets* property so that the Kafka broker can read the key and cert from it. Setting this property to e.g. `"{{ include \"hono.fullname\" . }}-kafka-example-keys"`, however, results in the Kafka broker trying to mount a Secret with name `eclipse-hono-kafka-kafka-example-keys`.

Based on my analysis, the (undesired) `eclipse-hono-kafka` prefix is produced by the *hono.fullname* named template being evaluated with the property values as seen by the Kafka chart. These are the values from the Kafka chart's own `values.yaml` file overridden by the properties defined under `kafka` in the Hono chart's `values.yaml`. The problem with this is that the Kafka chart does not find a value for the *fullnameOverride* property but only for the *nameOverride* property (*kafka.nameOverride* has value `kafka`).

In order to solve this problem, we could use a static name for this particular Secret that we can then also use for the *kafka.auth.tls.existingSecrets* property. This would require us to either adapt the *hono.metadata* named template accordingly or to manually set the Secret's metadata in the template. This would also result in the intended naming pattern to not be applied across all the chart's resources consistently.

Alternatively, we could use [*global* variables](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values) in the Hono chart to override the default prefix. These global variables could then be uniformly accessed from both the Hono chart's and the Kafka chart's templates using *.Values.global.nameOverride* and *.Values.global.fullnameOverride*.

@calohmn Do you agree with the analysis? Do you see any other options for fixing the problem?

BTW I haven't found any recommended [Best Practices](https://helm.sh/docs/chart_best_practices/) regarding the naming of resources in the Helm documentation. So I wonder if any of these approaches is actually worth the effort, given that we do not have a compelling use case for actually overriding the prefix being used in resource names.

**Comment by sophokles73** [comment]
@calohmn any thoughts?

**Comment by calohmn** [comment]
So, the root of the problem here is that Helm doesn't properly support templating in values.yaml (https://github.com/helm/helm/issues/2492) and also doesn't support passing computed/derived parameter values from parent to subchart (https://github.com/helm/helm/issues/6699).
The fact that the `hono.fullname` named template is evaluated in the  `kafka.auth.tls.existingSecrets` values.yaml value at all, is because the Kafka subchart runs the `tpl` function on that value. And the subchart only has access to its own or global values, not to the parent Hono-chart values, hence the unwanted output.

Reading about this topic and doing some tests (also with dynamically adapting `.Values.global`), I didn't find another solution. So, I agree with the above analysis and the given kinds of solutions.

Regarding the first solution:
Instead of a completely static name, we could also just let the `hono.metadata` and `hono.fullname` named templates accept an optional `nameOverrideContext` parameter, which could be set to the `kafka` values dict (from the Hono chart perspective), so that the `kafka-example-keys` Secret name would be created using `kafka.nameOverride`/`kafka.fullnameOverride`. As the `kafka-example-keys` Secret also kind of belongs to the Kafka chart, letting it adhere to the Kafka naming scheme wouldn't be an issue in terms of overall naming consistency, I think.

Regarding the second solution:
I would suggest adding `hono` in the property names, e.g. `.Values.global.hono.nameOverride`; the name override is only meant for Hono resources after all.

All in all, both solutions are fine with me. I would probably go with the first (letting the overrides stay in Hono values directly, not in `global`).

**Comment by vhdirk** [comment]
@calohmn I've modified the PR to let hono.name and hono.fullname accept template strings rather than static strings. I don't quite understand how you envision implementing the `nameOverrideContext` suggestion. Could you clarify some more?

**Comment by calohmn** [comment]
> I don't quite understand how you envision implementing the `nameOverrideContext` suggestion. Could you clarify some more?

My idea was to add an optional parameter of type `dict` to the `hono.fullname` named template (and also to `hono.metadata`), so that `fullnameOverride`, `nameOverride` isn't taken from `.Values` but from the given dict parameter if set.
Trying this out, this looks like a bigger change than I initially thought.

But I got another idea:
Since we only have to change the name concerning the `kafka-example-keys` Secret, we could adapt the `dot` `$args` dict entry there that provides the data to derive the name from.
That means instead of
`  {{- $args := dict "dot" . [...]`
we could use
`  {{- $args := dict "dot" (. | deepCopy | merge (dict "Values" (pick .Values.kafka "nameOverride" "fullnameOverride"))) [...]`.

This overwrites  the `.dot.Values.nameOverride` and `.dot.Values.fullnameOverride` values with the ones from `.Values.kafka`.

**Comment by sophokles73** [comment]
> This is an alternative solution to the changes you made in the PR towards using .Values.global.hono.

This sounds good to me. However, IMHO we would need to add a comment explaining what we are doing ...

@vhdirk can you adapt/update your PR accordingly (and also rebase it)?

**Comment by vhdirk** [comment]
@sophokles73 @calohmn 
I've rebased the PR and changed it according to the suggestion of @calohmn. I had to do some weird `gotpl` magic in `charts/hono/templates/hono-service-device-registry-base/hono-service-device-registry-post-install-configmap.yaml` in order to make it work, but I think this should do the trick.
