### ISSUE TITLE
When installing to minikube... "Error: INSTALLATION FAILED: timed out waiting for the condition"

### ISSUE THREAD

**Issue by mmcc-xx** [eclipse/packages#459]
Warning: I'm pretty new to kubernetes

I'm trying to get cloud2edge installed using minikube running in an Azure ubuntu VM. The VM has 16GM of RAM and 4 CPUs.

I've allocated 12GB of ram and 4 CPUs to minikube with...
minikube config set memory 12288
minikube config set cpus 4

I run 'minikube delete' to remove any existing cluster
I run 'minikube start' to get a clean cluster up and running
I create the namespace per https://www.eclipse.org/packages/packages/cloud2edge/installation/
I then attempt to install with the commands listed under the NodePort command.

After a 15 minute wait, I get the error "INSTALLATION FAILED: timed out waiting for the condition"

During the wait, if I run 'kubectl get pods -n $NS' I see that the c2e-kafka-0 pod is in the Init:0/1 status and its number of restarts goes up.  All of the other pods are Running.

It looks like I have plenty of free memory and disk space.

I've got ubuntu 22.04, minikube v1.29.0, Kubernetes v1.26.1, Docker 20.10.23, helm v3.11.2, kubectl client v1.26.3, kubectl server v1.26.1

Any suggestions for fixing this?

**Comment by mmcc-xx** [comment]
More info:
Same thing happens with the kafka pod if I try to install just the hono package.
However, I can install successfully install the kafka chart from bitnami directly
`helm repo add bitnami https://charts.bitnami.com/bitnami`
`helm install my-release bitnami/kafka`

**Comment by BHUVANESHWARI967** [comment]
Hi,

I am facing the same issue, but I have tried to install the cloud2edge package on kubernetes instead of lightweight kubernetes. I have raised an issue [https://github.com/eclipse/packages/issues/481](url). Could you please take a look at this and it would be helpful if you could provide some insight.

**Comment by calohmn** [comment]
@mmcc-xx Since version 0.6.0 of the cloud2edge chart, the default is now the NodePort configuration (not requiring `minikube tunnel`). On the [installation page](https://www.eclipse.org/packages/packages/cloud2edge/installation/#variants-1-1), in the tab describing the installation with the LoadBalancer configuration, it is now mentioned that on Minikube `minikube tunnel` should be used.

Can this be closed then?
