### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims ==> eclipse-hono-service-device-registry-0

### ISSUE THREAD

**Issue by eliot4321** [eclipse/packages#83]
Hi,

After deploying  hono  I got this error " "VolumeBinding" filter plugin for pod "eclipse-hono-service-device-registry-0": pod has unbound immediate PersistentVolumeClaims " on "eclipse-hono-service-device-registry-0" pod.

Any idea to fix this?

**Comment by calohmn** [comment]
Are you using minikube? I had this issue recently, having updated minikube to 1.8.2, while keeping an existing cluster. I noticed that I had 2 nodes (`k get no` - "minikube" and the new default "m01"), so maybe the issue had something to do with that. 
Deleting the minikube cluster and recreating it solved it for me. An update to minikube 1.9 might also work - the issues with updating an older cluster are supposedly fixed in that version.

**Comment by eliot4321** [comment]
Hi,
Thanks for the reply.
I'm not using minikube I'm using  a kuberenetes cluster of two nodes 1 master and 1 slave running in Openstack.

**Comment by sophokles73** [comment]
can you post the output of `kubectl describe pvc eclipse-hono-service-device-registry` and `kc get storageclass`?

**Comment by eliot4321** [comment]
1. kubectl describe pvc eclipse-hono-service-device-registry
Name:          eclipse-hono-service-device-registry
Namespace:     default
StorageClass:  manual
Status:        Bound
Volume:        eclipse-hono-service-device-registry
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    <none>
Events:        <none>

2. kubectl get storageclass -n hono
No resources found in hono namespace.

**Comment by sophokles73** [comment]
The storage classes are not defined in the hono namespace so please just do a `kubectl get storageclass`

**Comment by eliot4321** [comment]
Hi,

kubectl get storageclass
No resources found in default namespace.

**Comment by sophokles73** [comment]
Then I guess that this is the problem. Your Openshift cluster doesn't seem to support creation of persistent volumes. You will need to figure out how you can enable/configure that with the provider of your cluster (if it is a managed service). Otherwise, you will probably need to figure it out yourself by studying the Openshift docs. Or maybe @ctron has some idea?

**Comment by eliot4321** [comment]
Thanks. for the reply, but I'm not using OpenShift.

**Comment by sophokles73** [comment]
sorry, confused your issue with somebody else's ... The main problem remains the same.

**Comment by sophokles73** [comment]
@eliot4321 is this still an issue?

**Comment by eliot4321** [comment]
Hi,
I managed to solve the issue, but many others fired. I guess there is challenges with Eclipse HONO deployment in OpenStack. 
I'm preparing the list of the errors that I will share as soon as I finish.

**Comment by sophokles73** [comment]
@eliot4321 can this issue be closed?
